VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "logger" do |logger|
	  logger.vm.box = "ubuntu/precise64"
	  logger.vm.hostname = "logger.dev"
	  logger.vm.provision :shell, path: "bootstrap.sh"
	  logger.vm.network :private_network, ip:"192.168.46.46"
	  logger.vm.network :forwarded_port, host: 8092, guest: 8092
	  logger.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 1
		v.name = "loggerBox"
      end
  end
end