VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "logger" do |logger|
	  logger.vm.box = "ubuntu/precise64"
	  logger.vm.hostname = "logger.dev"
	  logger.vm.provision :shell, path: "logger-bootstrap.sh"
	  logger.vm.network :private_network, ip:"192.168.46.46"
	  logger.vm.network :forwarded_port, host: 14600, guest: 14600
	  logger.vm.synced_folder "../", "/vagrant/pzlogger"
	  logger.vm.provider "virtualbox" do |v|
	  	v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		v.customize ["modifyvm", :id, "--memory", "512"]
      end
  end
end